version: '3.8'
services:
  web:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: web
    depends_on:
      - db
    volumes:
      - ./php:/var/www/html/
    ports:
      - 8080:80

  db:
    container_name: db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: test_db
      MYSQL_USER: testuser
      MYSQL_PASSWORD: secret
    ports:
      - 6033:3306  
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    restart: always
    depends_on:
      - db
    ports:
      - 8000:80
    environment: 
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_PORT=3306
volumes:
  dbdata: